### ISSUE TITLE
Running choco push on Linux results in System.IO.IOException - "The filename, directory name, or volume label syntax is incorrect"

### ISSUE THREAD

**Issue by jsyeo** [chocolatey/nuget-chocolatey#17]
I am trying to push a nupkg file that I've created using this library to the chocolatey source on a linux machine and I am a `System.IO.IOException`. Here's the code that I'm using.

```csharp
class Program
{
    static void Main(string[] args)
    {
	    var packageServer = new PackageServer("https://push.chocolatey.org/", "Chocolatey Command Line");

	    var package = new OptimizedZipPackage("/home/yo/my-package.nupkg");

	    const bool disableBuffering = false;

	    packageServer.PushPackage(
	        "cafe-babe-0000-8888-9999",
	        package,
	        new FileInfo(outputFile).Length,
	        Convert.ToInt32(TimeSpan.FromMinutes(300).TotalMilliseconds),
	        disableBuffering);

	    Console.WriteLine("Successfully pushed nupkg file to: " + source);
        }
}
```

Here's the stacktrace:
```
Unhandled Exception: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect : 'Global\LOFCMFM/FUVENPCKQ0HKDLFJCEIYXTTN8KFD2P72L94='
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at NuGet.Settings.ExecuteSynchronized(Action ioOperation)
   at NuGet.Settings..ctor(IFileSystem fileSystem, String fileName, Boolean isMachineWideSettings)
   at NuGet.Settings.ReadSettings(IFileSystem fileSystem, String settingsPath, Boolean isMachineWideSettings)
   at NuGet.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, IFileSystem fileSystem, String configFileName)
   at NuGet.Settings.LoadDefaultSettings(IFileSystem fileSystem, String configFileName, IMachineWideSettings machineWideSettings)
   at NuGet.ProxyCache.<>c.<.cctor>b__20_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at NuGet.HttpClient.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
   at NuGet.RedirectedHttpClient.get_CachedClient()
   at NuGet.PackageServer.ResolveBaseUrl()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at NuGet.PackageServer.GetClient(String path, String method, String contentType)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at mini_choco.Program.Main(String[] args) in /home/yo/repos/mini-choco/Program.cs:line 35
```

I suspect it's because there are slashes in the mutex name. See https://github.com/NLog/NLog/issues/1882. Seems like the NLog guys are facing the same issue on OSX.

**Comment by gep13** [comment]
@TheCakeIsNaOH is this a problem that you have seen with the work that you have been doing, and pushing packages on Linux machines?

**Comment by TheCakeIsNaOH** [comment]
@gep13 no, I have not seen this. Doing some debugging and looking through the code, the only time this seems to be used for is to lock the `NuGet.Config` file, which is not actually used, so the change in the PR should be fine?

**Comment by gep13** [comment]
The NuGet.config file isn't used anymore at all within the Chocolatey code base. An earlier change prevented the creation of it at all, so I don't think this change is needed at all anymore. Right?

**Comment by TheCakeIsNaOH** [comment]
The function does still run if `NuGet.Config` already exists. So 🤷
